language: python
python:
  - "3.5"

before_install:
  - ./build_etcd.sh v3.1.1

# command to install dependencies
install:
  - pip install coveralls
  - pip install coverage
  - pip install pyOpenSSL
  - pip install 'git+https://github.com/jplana/python-etcd.git'
  - python setup.py build

# command to run tests
script:
  PATH=$PATH:./etcd/bin python ./setup.py test

after_success: coveralls

# Add env var to detect travis during build
env: TRAVIS=True
sudo: false
